site_name: National Hydrological Service Practitioners Guide
site_url: https://nhs-dev.github.io/NHS-Practitioners-Guide/
site_description: National Hydrological Service Pracititioners guide 

# name of the remote set in your fork where the documentation will actually be deployed
# validate value with `git remote -v`, it must be pointing to https://github.com/NHS-Dev/NHS-Practitioners-Guide.git
#required libraries 
# mkdocs
# mkdocs-material
# mkdocs-table-reader-plugin: 
# tags : pip install git+https://github.com/jldiaz/mkdocs-plugin-tags.git
remote_name: origin

nav: 
    - Home: index.md
    - Available Products: 
        - NSRPS: products/NSRPS/nsrps-3.1.0.md
        - Subsystems:
            - DHPS: products/DHPS/DHPS-3.1.0.md
    - Data Access: data_access/data_access.md 
    - Additional Information: 
        - Glossary: additional_information/glossary/glossary.md 
        - Operation Statuses: additional_information/Op_status/op-status.md
        - License: license/license.md
    - Usage and Tutorials: 
        - Example page: usage_and_tutorials/test.md
theme: 
    name: material
    palette:
        primary: blue grey
    favicon: assets/favicon.png
    features:
        - navigation.tabs
        - content.tabs.link
        - navigation.top
plugins:
    - search 
    - table-reader
    - tags
    
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - meta
    
extra:
    generator: false
    

#required libraries 
# mkdocs
# mkdocs-material
# mkdocs-table-reader-plugin