site_name: National Hydrological Service Practitioners Guide
site_url: https://nhs-dev.github.io/NHS-Practitioners-Guide/
site_description: >-
    National Hydrological Service Pracititioners guide to CMC prediction products. 

# name of the remote set in your fork where the documentation will actually be deployed
# validate value with `git remote -v`, it must be pointing to https://github.com/NHS-Dev/NHS-Practitioners-Guide.git
#required libraries 
# mkdocs
# mkdocs-material
# mkdocs-table-reader-plugin: 
# tags : pip install git+https://github.com/jldiaz/mkdocs-plugin-tags.git

# Repository
remote_name: origin
repo_url: https://github.com/NHS-Dev/NHS-Practitioners-Guide
edit_uri: ""

nav: 
    - Home: index.md
    - About: about.md
    - Available Data: available-datasets.md
    - Data Access: 
        - Data Mart: coming-soon.md
        - Geomet: coming-soon.md 
        - File Formats and naming: data_access/file_formats/file_formats.md
    - Data Usage and Tutorials: coming-soon.md 
    - Additional Information: 
        - Glossary: additional_information/glossary/glossary.md 
        - Operation Statuses: additional_information/operational-statuses/operational-status.md
        - License: license/license.md

theme: 
    name: null
    custom_dir: custom_theme
    favicon: assets/favicon.png
    static_templates:
       - 404.html
       
    plugins:
        - search 
        - tags 
        
    include_search_page: true
    search_index_only: false
      
    
        

#required libraries 
# mkdocs
# mkdocs-material
# mkdocs-table-reader-plugin